name: ⭐️ Catch Errors ⭐️

on:
  workflow_call
    
env:
  GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   catch-errors:
      name: comments
      runs-on: ubuntu-latest

      steps:
        - name: sync
          uses: actions/checkout@v2
        - name: evaluate
          if: success()
          env:
            GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
          run: |
           gh run view ${{github.run_id}} > results.txt
           gh issue comment ${{github.event.issue.number}} -F results.txt
           gh issue edit ${{github.event.issue.number}} --add-label done 
           gh issue edit ${{github.event.issue.number}} --remove-label 'in Progress' 
           gh issue edit ${{github.event.issue.number}} --title "✅ ${{ github.event.issue.title }} - Run Completed "
        - name: catch-error
          if: failure()
          env:
            GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
          run: |
           gh run view ${{github.run_id}} --exit-status > error.txt
           gh issue comment ${{github.event.issue.number}} -F error.txt
           gh issue edit ${{github.event.issue.number}} --add-label invalid 
           gh issue edit ${{github.event.issue.number}} --remove-label 'in Progress' 
           gh issue edit ${{github.event.issue.number}} --title "⚠️ ${{ github.event.issue.title }} - Invalid run "
   
   



